tablereference:
    pattern:  /
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:index" }

tablereference_show:
    pattern:  /{id}/show
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:show" }

tablereference_new:
    pattern:  /new
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:new" }

tablereference_create:
    pattern:  /create
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:create" }
    requirements: { _method: post }

tablereference_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:edit" }

tablereference_update:
    pattern:  /{id}/update
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:update" }
    requirements: { _method: post|put }

tablereference_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GTGestionTournoisBundle:TableReference:delete" }
    requirements: { _method: post|delete }
