tournois:
    pattern:  /
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:index" }

tournois_show:
    pattern:  /{id}/show
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:show" }

tournois_new:
    pattern:  /new
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:new" }

tournois_create:
    pattern:  /create
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:create" }
    requirements: { _method: post }

tournois_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:edit" }

tournois_update:
    pattern:  /{id}/update
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:update" }
    requirements: { _method: post|put }

tournois_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GTGestionTournoisBundle:Tournois:delete" }
    requirements: { _method: post|delete }
