Tournois:
    type: entity
    table: tournois
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        intitule:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: INTITULE
        dtDebut:
            type: date
            nullable: false
            column: DT_DEBUT
        dtFin:
            type: date
            nullable: false
            column: DT_FIN
        nbrEquipe:
            type: integer
            unsigned: false
            nullable: false
            column: NBR_EQUIPE
        responsable:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: RESPONSABLE
        etat:
            type: boolean
            nullable: true
            column: ETAT
        commentaire:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: COMMENTAIRE
        str1:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: STR_1
        str2:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: STR_2
        int1:
            type: integer
            unsigned: false
            nullable: true
            column: INT_1
        int2:
            type: integer
            unsigned: false
            nullable: true
            column: INT_2
        dtCreation:
            type: datetime
            nullable: false
            column: DT_CREATION
    manyToOne:
        buteur:
            targetEntity: Joueurs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                BUTEUR:
                    referencedColumnName: ID
            orphanRemoval: false
        categorie:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                CATEGORIE:
                    referencedColumnName: ID
            orphanRemoval: false
        meilleurGardienne:
            targetEntity: Joueurs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                MEILLEUR_GARDIENNE:
                    referencedColumnName: ID
            orphanRemoval: false
        meilleurJoueur:
            targetEntity: Joueurs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                MEILLEUR_JOUEUR:
                    referencedColumnName: ID
            orphanRemoval: false
        systeme:
            targetEntity: Systeme
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                SYSTEME:
                    referencedColumnName: ID
            orphanRemoval: false
        winner:
            targetEntity: Equipes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                WINNER:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
