<?php

namespace GT\GestionTournoisBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TournoisController__JMSInjector
{
    public static function inject($container) {
        $instance = new \GT\GestionTournoisBundle\Controller\TournoisController();
        return $instance;
    }
}
