<?php

namespace Proxies\__CG__\GT\GestionTournoisBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Equipes extends \GT\GestionTournoisBundle\Entity\Equipes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setAssociation($association)
    {
        $this->__load();
        return parent::setAssociation($association);
    }

    public function getAssociation()
    {
        $this->__load();
        return parent::getAssociation();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setCoach($coach)
    {
        $this->__load();
        return parent::setCoach($coach);
    }

    public function getCoach()
    {
        $this->__load();
        return parent::getCoach();
    }

    public function setCin($cin)
    {
        $this->__load();
        return parent::setCin($cin);
    }

    public function getCin()
    {
        $this->__load();
        return parent::getCin();
    }

    public function setPhoto($photo)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function setPhotoEquipe($photoEquipe)
    {
        $this->__load();
        return parent::setPhotoEquipe($photoEquipe);
    }

    public function getPhotoEquipe()
    {
        $this->__load();
        return parent::getPhotoEquipe();
    }

    public function setLogo($logo)
    {
        $this->__load();
        return parent::setLogo($logo);
    }

    public function getLogo()
    {
        $this->__load();
        return parent::getLogo();
    }

    public function setLienPhoto($lienPhoto)
    {
        $this->__load();
        return parent::setLienPhoto($lienPhoto);
    }

    public function getLienPhoto()
    {
        $this->__load();
        return parent::getLienPhoto();
    }

    public function setLienPhotoEquipe($lienPhotoEquipe)
    {
        $this->__load();
        return parent::setLienPhotoEquipe($lienPhotoEquipe);
    }

    public function getLienPhotoEquipe()
    {
        $this->__load();
        return parent::getLienPhotoEquipe();
    }

    public function setLienLogo($lienLogo)
    {
        $this->__load();
        return parent::setLienLogo($lienLogo);
    }

    public function getLienLogo()
    {
        $this->__load();
        return parent::getLienLogo();
    }

    public function setOrders($orders)
    {
        $this->__load();
        return parent::setOrders($orders);
    }

    public function getOrders()
    {
        $this->__load();
        return parent::getOrders();
    }

    public function setStr1($str1)
    {
        $this->__load();
        return parent::setStr1($str1);
    }

    public function getStr1()
    {
        $this->__load();
        return parent::getStr1();
    }

    public function setStr2($str2)
    {
        $this->__load();
        return parent::setStr2($str2);
    }

    public function getStr2()
    {
        $this->__load();
        return parent::getStr2();
    }

    public function setStr3($str3)
    {
        $this->__load();
        return parent::setStr3($str3);
    }

    public function getStr3()
    {
        $this->__load();
        return parent::getStr3();
    }

    public function setInt1($int1)
    {
        $this->__load();
        return parent::setInt1($int1);
    }

    public function getInt1()
    {
        $this->__load();
        return parent::getInt1();
    }

    public function setInt2($int2)
    {
        $this->__load();
        return parent::setInt2($int2);
    }

    public function getInt2()
    {
        $this->__load();
        return parent::getInt2();
    }

    public function setDtCreation($dtCreation)
    {
        $this->__load();
        return parent::setDtCreation($dtCreation);
    }

    public function getDtCreation()
    {
        $this->__load();
        return parent::getDtCreation();
    }

    public function setTournoi(\GT\GestionTournoisBundle\Entity\Tournois $tournoi = NULL)
    {
        $this->__load();
        return parent::setTournoi($tournoi);
    }

    public function getTournoi()
    {
        $this->__load();
        return parent::getTournoi();
    }

    public function setGroupe($groupe)
    {
        $this->__load();
        return parent::setGroupe($groupe);
    }

    public function getGroupe()
    {
        $this->__load();
        return parent::getGroupe();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'association', 'adresse', 'coach', 'cin', 'photo', 'photoEquipe', 'logo', 'lienPhoto', 'lienPhotoEquipe', 'lienLogo', 'orders', 'str1', 'str2', 'str3', 'int1', 'int2', 'dtCreation', 'groupe', 'tournoi');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}