<?php

namespace Proxies\__CG__\GT\GestionTournoisBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Tournois extends \GT\GestionTournoisBundle\Entity\Tournois implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIntitule($intitule)
    {
        $this->__load();
        return parent::setIntitule($intitule);
    }

    public function getIntitule()
    {
        $this->__load();
        return parent::getIntitule();
    }

    public function setDtDebut($dtDebut)
    {
        $this->__load();
        return parent::setDtDebut($dtDebut);
    }

    public function getDtDebut()
    {
        $this->__load();
        return parent::getDtDebut();
    }

    public function setDtFin($dtFin)
    {
        $this->__load();
        return parent::setDtFin($dtFin);
    }

    public function getDtFin()
    {
        $this->__load();
        return parent::getDtFin();
    }

    public function setCategorie($categorie)
    {
        $this->__load();
        return parent::setCategorie($categorie);
    }

    public function getCategorie()
    {
        $this->__load();
        return parent::getCategorie();
    }

    public function setSysteme($systeme)
    {
        $this->__load();
        return parent::setSysteme($systeme);
    }

    public function getSysteme()
    {
        $this->__load();
        return parent::getSysteme();
    }

    public function setNbrEquipe($nbrEquipe)
    {
        $this->__load();
        return parent::setNbrEquipe($nbrEquipe);
    }

    public function getNbrEquipe()
    {
        $this->__load();
        return parent::getNbrEquipe();
    }

    public function setResponsable($responsable)
    {
        $this->__load();
        return parent::setResponsable($responsable);
    }

    public function getResponsable()
    {
        $this->__load();
        return parent::getResponsable();
    }

    public function setEtat($etat)
    {
        $this->__load();
        return parent::setEtat($etat);
    }

    public function getEtat()
    {
        $this->__load();
        return parent::getEtat();
    }

    public function setWinner($winner)
    {
        $this->__load();
        return parent::setWinner($winner);
    }

    public function getWinner()
    {
        $this->__load();
        return parent::getWinner();
    }

    public function setMeilleurJoueur($meilleurJoueur)
    {
        $this->__load();
        return parent::setMeilleurJoueur($meilleurJoueur);
    }

    public function getMeilleurJoueur()
    {
        $this->__load();
        return parent::getMeilleurJoueur();
    }

    public function setMeilleurGardienne($meilleurGardienne)
    {
        $this->__load();
        return parent::setMeilleurGardienne($meilleurGardienne);
    }

    public function getMeilleurGardienne()
    {
        $this->__load();
        return parent::getMeilleurGardienne();
    }

    public function setButeur($buteur)
    {
        $this->__load();
        return parent::setButeur($buteur);
    }

    public function getButeur()
    {
        $this->__load();
        return parent::getButeur();
    }

    public function setCommentaire($commentaire)
    {
        $this->__load();
        return parent::setCommentaire($commentaire);
    }

    public function getCommentaire()
    {
        $this->__load();
        return parent::getCommentaire();
    }

    public function setStr1($str1)
    {
        $this->__load();
        return parent::setStr1($str1);
    }

    public function getStr1()
    {
        $this->__load();
        return parent::getStr1();
    }

    public function setStr2($str2)
    {
        $this->__load();
        return parent::setStr2($str2);
    }

    public function getStr2()
    {
        $this->__load();
        return parent::getStr2();
    }

    public function setInt1($int1)
    {
        $this->__load();
        return parent::setInt1($int1);
    }

    public function getInt1()
    {
        $this->__load();
        return parent::getInt1();
    }

    public function setInt2($int2)
    {
        $this->__load();
        return parent::setInt2($int2);
    }

    public function getInt2()
    {
        $this->__load();
        return parent::getInt2();
    }

    public function setDtCreation($dtCreation)
    {
        $this->__load();
        return parent::setDtCreation($dtCreation);
    }

    public function getDtCreation()
    {
        $this->__load();
        return parent::getDtCreation();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'intitule', 'dtDebut', 'dtFin', 'nbrEquipe', 'responsable', 'etat', 'commentaire', 'str1', 'str2', 'int1', 'int2', 'dtCreation', 'buteur', 'categorie', 'meilleurGardienne', 'meilleurJoueur', 'systeme', 'winner');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}