GT\GestionTournoisBundle\Entity\But:
    type: entity
    table: but
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        nbrBut:
            type: integer
            unsigned: false
            nullable: false
            column: NBR_BUT
        str1:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_1
        str2:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_2
        int1:
            type: integer
            unsigned: false
            nullable: true
            column: INT_1
        int2:
            type: integer
            unsigned: false
            nullable: true
            column: INT_2
        dtCreation:
            type: datetime
            nullable: false
            column: DT_CREATION
    manyToOne:
        equipe:
            targetEntity: Equipes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                EQUIPE:
                    referencedColumnName: ID
            orphanRemoval: false
        joueur:
            targetEntity: Joueurs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                JOUEUR:
                    referencedColumnName: ID
            orphanRemoval: false
        matchs:
            targetEntity: Matchs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                MATCHS:
                    referencedColumnName: ID
            orphanRemoval: false
        tournoi:
            targetEntity: Tournois
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TOURNOI:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
