GT\GestionTournoisBundle\Entity\Equipes:
    type: entity
    table: equipes
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: NOM
        association:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: ASSOCIATION
        adresse:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: ADRESSE
        coach:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: COACH
        cin:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: CIN
        photo:
            type: blob
            nullable: true
            column: PHOTO
        photoEquipe:
            type: blob
            nullable: true
            column: PHOTO_EQUIPE
        logo:
            type: blob
            nullable: true
            column: LOGO
        lienPhoto:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: LIEN_PHOTO
        lienPhotoEquipe:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: LIEN_PHOTO_EQUIPE
        lienLogo:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: LIEN_LOGO
        orders:
            type: integer
            unsigned: false
            nullable: false
            column: ORDERS
        str1:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_1
        str2:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_2
        str3:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_3
        int1:
            type: integer
            unsigned: false
            nullable: true
            column: INT_1
        int2:
            type: integer
            unsigned: false
            nullable: true
            column: INT_2
        dtCreation:
            type: datetime
            nullable: false
            column: DT_CREATION
    manyToOne:
        groupe:
            targetEntity: Groupe
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                GROUPE:
                    referencedColumnName: ID
            orphanRemoval: false
        tournoi:
            targetEntity: Tournois
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TOURNOI:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
