GT\GestionTournoisBundle\Entity\Joueurs:
    type: entity
    table: joueurs
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: NOM
        prenom:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: PRENOM
        dtNaissance:
            type: date
            nullable: false
            column: DT_NAISSANCE
        equipe:
            type: integer
            unsigned: false
            nullable: false
            column: EQUIPE
        categorie:
            type: integer
            unsigned: false
            nullable: false
            column: CATEGORIE
        numero:
            type: integer
            unsigned: false
            nullable: true
            column: NUMERO
        photo:
            type: blob
            nullable: true
            column: PHOTO
        lien:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: LIEN
        str1:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_1
        str2:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_2
        int1:
            type: integer
            unsigned: false
            nullable: true
            column: INT_1
        int2:
            type: integer
            unsigned: false
            nullable: true
            column: INT_2
        dtCreation:
            type: datetime
            nullable: false
            column: DT_CREATION
    lifecycleCallbacks: {  }
