GT\GestionTournoisBundle\Entity\Matchs:
    type: entity
    table: matchs
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        numero:
            type: integer
            unsigned: false
            nullable: false
            column: NUMERO
        dtMatch:
            type: date
            nullable: true
            column: DT_MATCH
        hMatch:
            type: time
            nullable: true
            column: H_MATCH
        arbitre:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: ARBITRE
        but1:
            type: integer
            unsigned: false
            nullable: true
            column: BUT_1
        but2:
            type: integer
            unsigned: false
            nullable: true
            column: BUT_2
        pin1:
            type: integer
            unsigned: false
            nullable: true
            column: PIN_1
        pin2:
            type: integer
            unsigned: false
            nullable: true
            column: PIN_2
        commentaire:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: COMMENTAIRE
        str1:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_1
        str2:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: STR_2
        int1:
            type: integer
            unsigned: false
            nullable: true
            column: INT_1
        int2:
            type: integer
            unsigned: false
            nullable: true
            column: INT_2
        dtCreation:
            type: datetime
            nullable: false
            column: DT_CREATION
    manyToOne:
        equipe1:
            targetEntity: Equipes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                EQUIPE1:
                    referencedColumnName: ID
            orphanRemoval: false
        equipe2:
            targetEntity: Equipes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                EQUIPE2:
                    referencedColumnName: ID
            orphanRemoval: false
        tour:
            targetEntity: Tour
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TOUR:
                    referencedColumnName: ID
            orphanRemoval: false
        tournoi:
            targetEntity: Tournois
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TOURNOI:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
